//! Seeds a set of example games on first launch so the library is not empty.
//!
//! Each game includes multiple localized/alternate names (see multi-name
//! design in docs/design/data-models.md) and a URL play action pointing to a
//! store page, so the user can try "Play" without installing anything.

use crate::models::{Game, GameAction, GameLink, GameName};
use chrono::Utc;

fn now() -> String {
    Utc::now().to_rfc3339()
}

fn url_action(url: &str) -> GameAction {
    GameAction {
        id: uuid::Uuid::new_v4().to_string(),
        name: "Play".into(),
        r#type: "URL".into(),
        path: Some(url.into()),
        working_dir: None,
        arguments: None,
        is_play_action: true,
        track_game: true,
    }
}

/// Builds the sample games. Each game's `name` is the primary (usually English)
/// title; `localized_names` / `alternate_names` showcase multi-name support and
/// enable Pinyin initials search (e.g. "星际争霸" -> xjzb).
pub fn sample_games() -> Vec<Game> {
    let stamp = now();
    vec![
        Game {
            id: "sample-gta5".into(),
            name: "Grand Theft Auto V".into(),
            sort_name: Some("Grand Theft Auto V".into()),
            localized_names: vec![
                GameName { language: "zh-CN".into(), name: "侠盗猎车手V".into() },
                GameName { language: "zh-TW".into(), name: "俠盜獵車手V".into() },
                GameName { language: "ja".into(), name: "グランド・セフト・オートV".into() },
                GameName { language: "ko".into(), name: "그랜드 테프트 오토 V".into() },
            ],
            alternate_names: vec!["三男一狗".into(), "车枪大战".into(), "GTA5".into(), "GTAV".into()],
            game_id: None,
            installed: false,
            install_directory: None,
            play_task: None,
            other_tasks: vec![],
            last_played: None,
            play_count: 0,
            last_activity: None,
            playtime: 0,
            added: stamp.clone(),
            modified: stamp.clone(),
            category: vec!["Open World".into()],
            genre: vec!["Action".into(), "Adventure".into()],
            developer: vec!["Rockstar North".into()],
            publisher: vec!["Rockstar Games".into()],
            tags: vec!["Open World".into(), "Multiplayer".into(), "Third Person".into()],
            series: vec!["Grand Theft Auto".into()],
            age_rating: vec!["M".into()],
            region: vec!["WW".into()],
            source: vec!["Manual".into()],
            features: vec!["Single Player".into()],
            release_date: Some("2013-09-17".into()),
            community_score: Some(89),
            critic_score: Some(96),
            user_score: None,
            hidden: false,
            favorite: true,
            background_image: None,
            cover_image: None,
            icon: None,
            description: Some(
                "An open-world action-adventure game set in the fictional state of San Andreas. \
                 Follow three criminals as they pull off a series of heists across Los Santos."
                    .into(),
            ),
            notes: None,
            version: None,
            platform: vec!["PC".into()],
            emulator: None,
            completion_status: Some("NotStarted".into()),
            user_score_set: false,
            manual_game: true,
            plugin_id: None,
            links: vec![GameLink { name: "Steam".into(), url: "https://store.steampowered.com/app/271590".into() }],
            actions: vec![url_action("https://store.steampowered.com/app/271590")],
            features_enabled: true,
            guide: Some(
                "<h3>How to Play</h3><p>GTA V is an open-world action-adventure. Follow the \
                 story missions (marked by letters on the map) to progress through heists, or \
                 explore Los Santos freely.</p><h4>Controls</h4><ul><li><b>WASD</b> — move</li>\
                 <li><b>Mouse</b> — look / shoot</li><li><b>Shift</b> — run</li><li><b>F</b> — \
                 enter/exit vehicle</li><li><b>Tab</b> — switch character</li></ul>".into(),
            ),
            screenshots: vec![
                "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/271590/ss_1.jpg".into(),
                "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/271590/ss_2.jpg".into(),
                "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/271590/ss_3.jpg".into(),
            ],
            videos: vec![crate::models::GameVideo {
                r#type: "youtube".into(),
                url: "https://www.youtube.com/watch?v=QkkoHAzjnUs".into(),
                name: Some("Gameplay Trailer".into()),
            }],
            game_library: None,
            game_level: 1,
        },
        Game {
            id: "sample-starcraft".into(),
            name: "StarCraft II: Wings of Liberty".into(),
            sort_name: Some("StarCraft II".into()),
            localized_names: vec![
                GameName { language: "zh-CN".into(), name: "星际争霸II：自由之翼".into() },
                GameName { language: "zh-TW".into(), name: "星海爭霸II：自由之翼".into() },
                GameName { language: "ja".into(), name: "スタークラフトII".into() },
                GameName { language: "ko".into(), name: "스타크래프트 II".into() },
            ],
            alternate_names: vec!["星际争霸".into(), "星海争霸".into(), "SC2".into()],
            game_id: None,
            installed: false,
            install_directory: None,
            play_task: None,
            other_tasks: vec![],
            last_played: None,
            play_count: 0,
            last_activity: None,
            playtime: 0,
            added: stamp.clone(),
            modified: stamp.clone(),
            category: vec!["Strategy".into()],
            genre: vec!["Real-Time Strategy".into(), "Science Fiction".into()],
            developer: vec!["Blizzard Entertainment".into()],
            publisher: vec!["Blizzard Entertainment".into()],
            tags: vec!["RTS".into(), "Multiplayer".into(), "Esports".into()],
            series: vec!["StarCraft".into()],
            age_rating: vec!["T".into()],
            region: vec!["WW".into()],
            source: vec!["Manual".into()],
            features: vec!["Single Player".into(), "Multiplayer".into()],
            release_date: Some("2010-07-27".into()),
            community_score: Some(86),
            critic_score: Some(93),
            user_score: None,
            hidden: false,
            favorite: false,
            background_image: None,
            cover_image: None,
            icon: None,
            description: Some(
                "A real-time strategy game set in the sci-fi Koprulu Sector. Command Terran, \
                 Zerg and Protoss armies in the struggle for dominance."
                    .into(),
            ),
            notes: None,
            version: None,
            platform: vec!["PC".into()],
            emulator: None,
            completion_status: Some("NotStarted".into()),
            user_score_set: false,
            manual_game: true,
            plugin_id: None,
            links: vec![GameLink { name: "Battle.net".into(), url: "https://starcraft2.blizzard.com" .into() }],
            actions: vec![url_action("https://starcraft2.blizzard.com")],
            features_enabled: true,
            guide: None,
            screenshots: Vec::new(),
            videos: Vec::new(),
            game_library: None,
            game_level: 1,
        },
        Game {
            id: "sample-cyberpunk".into(),
            name: "Cyberpunk 2077".into(),
            sort_name: Some("Cyberpunk 2077".into()),
            localized_names: vec![
                GameName { language: "zh-CN".into(), name: "赛博朋克2077".into() },
                GameName { language: "zh-TW".into(), name: "電馭叛客2077".into() },
                GameName { language: "ja".into(), name: "サイバーパンク2077".into() },
                GameName { language: "ko".into(), name: "사이버펑크 2077".into() },
            ],
            alternate_names: vec!["赛博朋克".into(), "夜之城".into(), "CP2077".into()],
            game_id: None,
            installed: false,
            install_directory: None,
            play_task: None,
            other_tasks: vec![],
            last_played: None,
            play_count: 0,
            last_activity: None,
            playtime: 0,
            added: stamp.clone(),
            modified: stamp.clone(),
            category: vec!["RPG".into()],
            genre: vec!["Role-Playing".into(), "Open World".into()],
            developer: vec!["CD Projekt Red".into()],
            publisher: vec!["CD Projekt".into()],
            tags: vec!["Cyberpunk".into(), "Open World".into(), "First Person".into()],
            series: vec!["Cyberpunk".into()],
            age_rating: vec!["M".into()],
            region: vec!["WW".into()],
            source: vec!["Manual".into()],
            features: vec!["Single Player".into()],
            release_date: Some("2020-12-10".into()),
            community_score: Some(86),
            critic_score: Some(86),
            user_score: None,
            hidden: false,
            favorite: true,
            background_image: None,
            cover_image: None,
            icon: None,
            description: Some(
                "An open-world action RPG set in Night City, a megalopolis obsessed with \
                 power, glamour and body modification."
                    .into(),
            ),
            notes: None,
            version: None,
            platform: vec!["PC".into()],
            emulator: None,
            completion_status: Some("NotStarted".into()),
            user_score_set: false,
            manual_game: true,
            plugin_id: None,
            links: vec![GameLink { name: "Steam".into(), url: "https://store.steampowered.com/app/1091500".into() }],
            actions: vec![url_action("https://store.steampowered.com/app/1091500")],
            features_enabled: true,
            guide: None,
            screenshots: Vec::new(),
            videos: Vec::new(),
            game_library: None,
            game_level: 1,
        },
        Game {
            id: "sample-witcher3".into(),
            name: "The Witcher 3: Wild Hunt".into(),
            sort_name: Some("The Witcher 3".into()),
            localized_names: vec![
                GameName { language: "zh-CN".into(), name: "巫师3：狂猎".into() },
                GameName { language: "zh-TW".into(), name: "巫師3：狂獵".into() },
                GameName { language: "ja".into(), name: "ウィッチャー3 ワイルドハント".into() },
                GameName { language: "ko".into(), name: "위쳐 3: 와일드 헌트".into() },
            ],
            alternate_names: vec!["巫师3".into(), "昆特牌启动器".into(), "Witcher 3".into()],
            game_id: None,
            installed: false,
            install_directory: None,
            play_task: None,
            other_tasks: vec![],
            last_played: None,
            play_count: 0,
            last_activity: None,
            playtime: 0,
            added: stamp.clone(),
            modified: stamp.clone(),
            category: vec!["RPG".into()],
            genre: vec!["Role-Playing".into(), "Action".into()],
            developer: vec!["CD Projekt Red".into()],
            publisher: vec!["CD Projekt".into()],
            tags: vec!["Open World".into(), "Fantasy".into(), "Story Rich".into()],
            series: vec!["The Witcher".into()],
            age_rating: vec!["M".into()],
            region: vec!["WW".into()],
            source: vec!["Manual".into()],
            features: vec!["Single Player".into()],
            release_date: Some("2015-05-19".into()),
            community_score: Some(95),
            critic_score: Some(93),
            user_score: None,
            hidden: false,
            favorite: false,
            background_image: None,
            cover_image: None,
            icon: None,
            description: Some(
                "An action role-playing game following monster hunter Geralt of Rivia as he \
                 searches for his adopted daughter amid a war-torn world."
                    .into(),
            ),
            notes: None,
            version: None,
            platform: vec!["PC".into()],
            emulator: None,
            completion_status: Some("NotStarted".into()),
            user_score_set: false,
            manual_game: true,
            plugin_id: None,
            links: vec![GameLink { name: "Steam".into(), url: "https://store.steampowered.com/app/292030".into() }],
            actions: vec![url_action("https://store.steampowered.com/app/292030")],
            features_enabled: true,
            guide: None,
            screenshots: Vec::new(),
            videos: Vec::new(),
            game_library: None,
            game_level: 1,
        },
        Game {
            id: "sample-eldenring".into(),
            name: "Elden Ring".into(),
            sort_name: Some("Elden Ring".into()),
            localized_names: vec![
                GameName { language: "zh-CN".into(), name: "艾尔登法环".into() },
                GameName { language: "zh-TW".into(), name: "艾爾登法環".into() },
                GameName { language: "ja".into(), name: "エルデンリング".into() },
                GameName { language: "ko".into(), name: "엘든 링".into() },
            ],
            alternate_names: vec!["老头环".into(), "法环".into()],
            game_id: None,
            installed: false,
            install_directory: None,
            play_task: None,
            other_tasks: vec![],
            last_played: None,
            play_count: 0,
            last_activity: None,
            playtime: 0,
            added: stamp.clone(),
            modified: stamp.clone(),
            category: vec!["RPG".into()],
            genre: vec!["Action Role-Playing".into(), "Open World".into()],
            developer: vec!["FromSoftware".into()],
            publisher: vec!["Bandai Namco".into()],
            tags: vec!["Soulslike".into(), "Open World".into(), "Difficult".into()],
            series: vec!["Elden Ring".into()],
            age_rating: vec!["M".into()],
            region: vec!["WW".into()],
            source: vec!["Manual".into()],
            features: vec!["Single Player".into()],
            release_date: Some("2022-02-25".into()),
            community_score: Some(92),
            critic_score: Some(96),
            user_score: None,
            hidden: false,
            favorite: false,
            background_image: None,
            cover_image: None,
            icon: None,
            description: Some(
                "An action RPG set in the Lands Between, where the demigods battle for the \
                 shattered Elden Ring."
                    .into(),
            ),
            notes: None,
            version: None,
            platform: vec!["PC".into()],
            emulator: None,
            completion_status: Some("NotStarted".into()),
            user_score_set: false,
            manual_game: true,
            plugin_id: None,
            links: vec![GameLink { name: "Steam".into(), url: "https://store.steampowered.com/app/1245620".into() }],
            actions: vec![url_action("https://store.steampowered.com/app/1245620")],
            features_enabled: true,
            guide: None,
            screenshots: Vec::new(),
            videos: Vec::new(),
            game_library: None,
            game_level: 1,
        },
        Game {
            id: "sample-celeste".into(),
            name: "Celeste".into(),
            sort_name: Some("Celeste".into()),
            localized_names: vec![
                GameName { language: "zh-CN".into(), name: "蔚蓝".into() },
                GameName { language: "zh-TW".into(), name: "蔚藍".into() },
                GameName { language: "ja".into(), name: "セレステ".into() },
            ],
            alternate_names: vec!["蔚蓝".into()],
            game_id: None,
            installed: false,
            install_directory: None,
            play_task: None,
            other_tasks: vec![],
            last_played: None,
            play_count: 0,
            last_activity: None,
            playtime: 0,
            added: stamp.clone(),
            modified: stamp.clone(),
            category: vec!["Indie".into()],
            genre: vec!["Platformer".into(), "Indie".into()],
            developer: vec!["Maddy Makes Games".into()],
            publisher: vec!["Maddy Makes Games".into()],
            tags: vec!["2D Platformer".into(), "Pixel Art".into(), "Precision".into()],
            series: vec![],
            age_rating: vec!["E10+".into()],
            region: vec!["WW".into()],
            source: vec!["Manual".into()],
            features: vec!["Single Player".into()],
            release_date: Some("2018-01-25".into()),
            community_score: Some(92),
            critic_score: Some(92),
            user_score: None,
            hidden: false,
            favorite: false,
            background_image: None,
            cover_image: None,
            icon: None,
            description: Some(
                "Help Madeline survive her journey to the top of Celeste Mountain in this \
                 tight, hand-crafted 2D platformer."
                    .into(),
            ),
            notes: None,
            version: None,
            platform: vec!["PC".into()],
            emulator: None,
            completion_status: Some("NotStarted".into()),
            user_score_set: false,
            manual_game: true,
            plugin_id: None,
            links: vec![GameLink { name: "Steam".into(), url: "https://store.steampowered.com/app/504230".into() }],
            actions: vec![url_action("https://store.steampowered.com/app/504230")],
            features_enabled: true,
            guide: None,
            screenshots: Vec::new(),
            videos: Vec::new(),
            game_library: None,
            game_level: 1,
        },
        Game {
            id: "sample-hades".into(),
            name: "Hades".into(),
            sort_name: Some("Hades".into()),
            localized_names: vec![
                GameName { language: "zh-CN".into(), name: "哈迪斯".into() },
                GameName { language: "zh-TW".into(), name: "黑帝斯".into() },
                GameName { language: "ja".into(), name: "ハデス".into() },
            ],
            alternate_names: vec!["黑帝斯".into()],
            game_id: None,
            installed: false,
            install_directory: None,
            play_task: None,
            other_tasks: vec![],
            last_played: None,
            play_count: 0,
            last_activity: None,
            playtime: 0,
            added: stamp.clone(),
            modified: stamp.clone(),
            category: vec!["Roguelike".into()],
            genre: vec!["Roguelike".into(), "Action".into()],
            developer: vec!["Supergiant Games".into()],
            publisher: vec!["Supergiant Games".into()],
            tags: vec!["Roguelike".into(), "Mythology".into()],
            series: vec![],
            age_rating: vec!["T".into()],
            region: vec!["WW".into()],
            source: vec!["Manual".into()],
            features: vec!["Single Player".into()],
            release_date: Some("2020-09-17".into()),
            community_score: Some(93),
            critic_score: Some(93),
            user_score: None,
            hidden: false,
            favorite: false,
            background_image: None,
            cover_image: None,
            icon: None,
            description: Some(
                "Defy the god of the dead as you hack and slash out of the Underworld in this \
                 fast-paced action roguelike."
                    .into(),
            ),
            notes: None,
            version: None,
            platform: vec!["PC".into()],
            emulator: None,
            completion_status: Some("NotStarted".into()),
            user_score_set: false,
            manual_game: true,
            plugin_id: None,
            links: vec![GameLink { name: "Steam".into(), url: "https://store.steampowered.com/app/1145360".into() }],
            actions: vec![url_action("https://store.steampowered.com/app/1145360")],
            features_enabled: true,
            guide: None,
            screenshots: Vec::new(),
            videos: Vec::new(),
            game_library: None,
            game_level: 1,
        },
    ]
}
