// Auto-generated by scripts/gen-styles.py — do not edit by hand.
// Sourced from the ui-ux-pro-max design system (67 style categories).
// Each style contributes non-color design variables (radius/glow/
// shadow/font); combining a palette + a style yields a full theme.

export interface StyleVars {
  radius: string;
  glow: string;
  shadow: string;
  font: string;
}

export interface StyleEntry {
  id: string;
  name: string;
  vars: StyleVars;
}

export const styleLibrary: StyleEntry[] = [
  {
    id: "s1",
    name: "Minimalism & Swiss Style",
    vars: {
      radius: "0px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s2",
    name: "Neumorphism",
    vars: {
      radius: "14px",
      glow: "none",
      shadow: "soft",
      font: "inherit",
    },
  },
  {
    id: "s3",
    name: "Glassmorphism",
    vars: {
      radius: "12px",
      glow: "none",
      shadow: "glass",
      font: "inherit",
    },
  },
  {
    id: "s4",
    name: "Brutalism",
    vars: {
      radius: "0px",
      glow: "none",
      shadow: "hard",
      font: "monospace",
    },
  },
  {
    id: "s5",
    name: "3D & Hyperrealism",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "deep",
      font: "inherit",
    },
  },
  {
    id: "s6",
    name: "Vibrant & Block-based",
    vars: {
      radius: "12px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s7",
    name: "Dark Mode (OLED)",
    vars: {
      radius: "8px",
      glow: "neon",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s8",
    name: "Accessible & Ethical",
    vars: {
      radius: "4px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s9",
    name: "Claymorphism",
    vars: {
      radius: "20px",
      glow: "none",
      shadow: "soft",
      font: "inherit",
    },
  },
  {
    id: "s10",
    name: "Aurora UI",
    vars: {
      radius: "12px",
      glow: "aurora",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s11",
    name: "Retro-Futurism",
    vars: {
      radius: "2px",
      glow: "neon",
      shadow: "neon",
      font: "monospace",
    },
  },
  {
    id: "s12",
    name: "Flat Design",
    vars: {
      radius: "4px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s13",
    name: "Skeuomorphism",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "deep",
      font: "inherit",
    },
  },
  {
    id: "s14",
    name: "Liquid Glass",
    vars: {
      radius: "14px",
      glow: "glass",
      shadow: "glass",
      font: "inherit",
    },
  },
  {
    id: "s15",
    name: "Motion-Driven",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s16",
    name: "Micro-interactions",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s17",
    name: "Inclusive Design",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s18",
    name: "Zero Interface",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s19",
    name: "Soft UI Evolution",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s20",
    name: "Hero-Centric Design",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s21",
    name: "Conversion-Optimized",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s22",
    name: "Feature-Rich Showcase",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s23",
    name: "Minimal & Direct",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s24",
    name: "Social Proof-Focused",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s25",
    name: "Interactive Product Demo",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s26",
    name: "Trust & Authority",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s27",
    name: "Storytelling-Driven",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s28",
    name: "Data-Dense Dashboard",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s29",
    name: "Heat Map & Heatmap Style",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s30",
    name: "Executive Dashboard",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s31",
    name: "Real-Time Monitoring",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s32",
    name: "Drill-Down Analytics",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s33",
    name: "Comparative Analysis Dashboard",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s34",
    name: "Predictive Analytics",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s35",
    name: "User Behavior Analytics",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s36",
    name: "Financial Dashboard",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s37",
    name: "Sales Intelligence Dashboard",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s38",
    name: "Neubrutalism",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s39",
    name: "Bento Box Grid",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s40",
    name: "Y2K Aesthetic",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s41",
    name: "Cyberpunk UI",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s42",
    name: "Organic Biophilic",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s43",
    name: "AI-Native UI",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s44",
    name: "Memphis Design",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s45",
    name: "Vaporwave",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s46",
    name: "Dimensional Layering",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s47",
    name: "Exaggerated Minimalism",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s48",
    name: "Kinetic Typography",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s49",
    name: "Parallax Storytelling",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s50",
    name: "Swiss Modernism 2.0",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s51",
    name: "HUD / Sci-Fi FUI",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s52",
    name: "Pixel Art",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s53",
    name: "Bento Grids",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s54",
    name: "Spatial UI (VisionOS)",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s55",
    name: "E-Ink / Paper",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s56",
    name: "Gen Z Chaos / Maximalism",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s57",
    name: "Biomimetic / Organic 2.0",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s58",
    name: "Anti-Polish / Raw Aesthetic",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s59",
    name: "Tactile Digital / Deformable UI",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s60",
    name: "Nature Distilled",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s61",
    name: "Interactive Cursor Design",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s62",
    name: "Voice-First Multimodal",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s63",
    name: "3D Product Preview",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s64",
    name: "Gradient Mesh / Aurora Evolved",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s65",
    name: "Editorial Grid / Magazine",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s66",
    name: "Chromatic Aberration / RGB Split",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
  {
    id: "s67",
    name: "Vintage Analog / Retro Film",
    vars: {
      radius: "8px",
      glow: "none",
      shadow: "none",
      font: "inherit",
    },
  },
];
