#!/usr/bin/env python3
"""Generate a style library from the ui-ux-pro-max styles.csv.

Reads styles.csv (67 style categories) and emits src/utils/styleLibrary.ts.
Each style contributes non-color design variables (border radius, glow,
shadow, font, etc.) that can be injected onto :root at runtime — independent
from the 96 color palettes. A "theme" = a palette + a style.

Usage:
    python3 scripts/gen-styles.py
"""
import csv
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STYLES_CSV = r"C:\Users\Administrator\.codebuddy\skills\ui-ux-pro-max\data\styles.csv"
OUT = os.path.join(ROOT, "src", "utils", "styleLibrary.ts")

# Map a style category to safe non-color variables (sane defaults derived from
# the ui-ux-pro-max "Design System Variables" guidance).
STYLE_DEFAULTS = {
    "Minimalism & Swiss Style": {"radius": "0px", "glow": "none", "shadow": "none", "font": "inherit"},
    "Neumorphism": {"radius": "14px", "glow": "none", "shadow": "soft", "font": "inherit"},
    "Glassmorphism": {"radius": "12px", "glow": "none", "shadow": "glass", "font": "inherit"},
    "Brutalism": {"radius": "0px", "glow": "none", "shadow": "hard", "font": "monospace"},
    "3D & Hyperrealism": {"radius": "8px", "glow": "none", "shadow": "deep", "font": "inherit"},
    "Vibrant & Block-based": {"radius": "12px", "glow": "none", "shadow": "none", "font": "inherit"},
    "Dark Mode (OLED)": {"radius": "8px", "glow": "neon", "shadow": "none", "font": "inherit"},
    "Accessible & Ethical": {"radius": "4px", "glow": "none", "shadow": "none", "font": "inherit"},
    "Claymorphism": {"radius": "20px", "glow": "none", "shadow": "soft", "font": "inherit"},
    "Aurora UI": {"radius": "12px", "glow": "aurora", "shadow": "none", "font": "inherit"},
    "Retro-Futurism": {"radius": "2px", "glow": "neon", "shadow": "neon", "font": "monospace"},
    "Flat Design": {"radius": "4px", "glow": "none", "shadow": "none", "font": "inherit"},
    "Skeuomorphism": {"radius": "8px", "glow": "none", "shadow": "deep", "font": "inherit"},
    "Liquid Glass": {"radius": "14px", "glow": "glass", "shadow": "glass", "font": "inherit"},
}


def parse_design_vars(raw: str) -> dict:
    """Extract --key: value pairs from the Design System Variables column."""
    out = {}
    if not raw:
        return out
    # Find --var: value fragments (value may contain spaces until next --).
    pairs = re.findall(r"--([a-z0-9-]+):\s*([^,]*?)(?=--[a-z0-9-]+:|$)", raw)
    for k, v in pairs:
        key = k.strip().replace("-", "")
        val = v.strip().strip(",")
        if key and val:
            out[key] = val
    return out


def main():
    styles = []
    seen = set()
    with open(STYLES_CSV, encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            category = (row.get("Style Category") or "").strip()
            if not category or category in seen:
                continue
            seen.add(category)
            defaults = STYLE_DEFAULTS.get(category, {"radius": "8px", "glow": "none", "shadow": "none", "font": "inherit"})
            design_vars = parse_design_vars(row.get("Design System Variables") or "")
            styles.append(
                {
                    "id": f"s{len(styles) + 1}",
                    "name": category,
                    "vars": {
                        "radius": design_vars.get("borderradius", defaults["radius"]),
                        "glow": defaults["glow"],
                        "shadow": defaults["shadow"],
                        "font": defaults["font"],
                    },
                }
            )

    lines = [
        "// Auto-generated by scripts/gen-styles.py — do not edit by hand.",
        "// Sourced from the ui-ux-pro-max design system (67 style categories).",
        "// Each style contributes non-color design variables (radius/glow/",
        "// shadow/font); combining a palette + a style yields a full theme.",
        "",
        "export interface StyleVars {",
        "  radius: string;",
        "  glow: string;",
        "  shadow: string;",
        "  font: string;",
        "}",
        "",
        "export interface StyleEntry {",
        "  id: string;",
        "  name: string;",
        "  vars: StyleVars;",
        "}",
        "",
        "export const styleLibrary: StyleEntry[] = [",
    ]
    for s in styles:
        lines.append(f"  {{")
        lines.append(f'    id: "{s["id"]}",')
        lines.append(f'    name: "{s["name"].replace(chr(34), chr(92) + chr(34))}",')
        lines.append("    vars: {")
        for k, v in s["vars"].items():
            lines.append(f'      {k}: "{v}",')
        lines.append("    },")
        lines.append("  },")
    lines.append("];")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {len(styles)} styles -> {OUT}")


if __name__ == "__main__":
    main()
