#!/usr/bin/env python3
"""Generate a theme library from the ui-ux-pro-max colors.csv palette set.

Reads the ui-ux-pro-max colors.csv (96 palettes) + styles.csv (67 style
categories) and emits src/utils/themeLibrary.ts with a structured list of
themes. Each theme maps the palette (primary/secondary/cta/background/text/
border) into the project's shadcn token + legacy business variable vocabulary,
so a clicked theme can be injected onto :root at runtime.

Usage:
    python3 scripts/gen-themes.py
"""
import csv
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COLORS_CSV = r"C:\Users\Administrator\.codebuddy\skills\ui-ux-pro-max\data\colors.csv"
STYLES_CSV = r"C:\Users\Administrator\.codebuddy\skills\ui-ux-pro-max\data\styles.csv"
OUT = os.path.join(ROOT, "src", "utils", "themeLibrary.ts")


def hex_to_rgba(h: str, a: float) -> str:
    h = h.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return f"rgba({r}, {g}, {b}, {a})"


def shade(h: str, factor: float) -> str:
    """Lighten (factor>1) or darken (factor<1) a hex color."""
    h = h.lstrip("#")
    r = min(255, int(int(h[0:2], 16) * factor))
    g = min(255, int(int(h[2:4], 16) * factor))
    b = min(255, int(int(h[4:6], 16) * factor))
    return f"#{r:02x}{g:02x}{b:02x}"


def main():
    palettes = []
    with open(COLORS_CSV, encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            name = (row.get("Product Type") or "").strip()
            primary = (row.get("Primary (Hex)") or "#6d5df6").strip()
            secondary = (row.get("Secondary (Hex)") or primary).strip()
            cta = (row.get("CTA (Hex)") or primary).strip()
            bg = (row.get("Background (Hex)") or "#0e0e16").strip()
            text = (row.get("Text (Hex)") or "#e6e7ee").strip()
            border = (row.get("Border (Hex)") or shade(text, 0.25)).strip()
            if not name:
                continue
            palettes.append(
                {
                    "name": name,
                    "primary": primary,
                    "secondary": secondary,
                    "cta": cta,
                    "bg": bg,
                    "text": text,
                    "border": border,
                }
            )

    # Build theme entries with derived tokens.
    entries = []
    for i, p in enumerate(palettes):
        primary, bg, text = p["primary"], p["bg"], p["text"]
        border = p["border"]
        accent = p["cta"]  # CTA doubles as accent for games.
        entries.append(
            {
                "id": f"p{i + 1}",
                "name": p["name"],
                "palette": {
                    "background": bg,
                    "foreground": text,
                    "card": shade(bg, 1.06),
                    "cardForeground": text,
                    "primary": primary,
                    "primaryForeground": "#ffffff",
                    "secondary": shade(bg, 1.12),
                    "secondaryForeground": text,
                    "muted": shade(bg, 1.08),
                    "mutedForeground": shade(text, 0.72),
                    "border": border,
                    "ring": primary,
                    # legacy business vars
                    "bgBase": bg,
                    "bgTop": shade(bg, 1.05),
                    "bgSidebar": shade(bg, 1.03),
                    "bgPanel": shade(bg, 1.06),
                    "bgItemHover": shade(bg, 1.14),
                    "bgItemActive": shade(bg, 1.2),
                    "bgInput": shade(bg, 1.04),
                    "borderStrong": shade(border, 1.25),
                    "textPrimary": text,
                    "textSecondary": shade(text, 0.85),
                    "textDim": shade(text, 0.7),
                    "accent": accent,
                    "accentHover": shade(accent, 1.15),
                    "accentSoft": hex_to_rgba(accent, 0.18),
                    "success": "#2fbf7f",
                    "warning": "#e0a63a",
                    "danger": "#e5484d",
                },
            }
        )

    lines = [
        "// Auto-generated by scripts/gen-themes.py — do not edit by hand.",
        "// Sourced from the ui-ux-pro-max design system (96 color palettes).",
        "// Each entry maps a palette onto the project's token vocabulary;",
        "// clicking a theme injects these onto :root at runtime.",
        "",
        "export interface ThemePaletteTokens {",
        "  background: string;",
        "  foreground: string;",
        "  card: string;",
        "  cardForeground: string;",
        "  primary: string;",
        "  primaryForeground: string;",
        "  secondary: string;",
        "  secondaryForeground: string;",
        "  muted: string;",
        "  mutedForeground: string;",
        "  border: string;",
        "  ring: string;",
        "  bgBase: string;",
        "  bgTop: string;",
        "  bgSidebar: string;",
        "  bgPanel: string;",
        "  bgItemHover: string;",
        "  bgItemActive: string;",
        "  bgInput: string;",
        "  borderStrong: string;",
        "  textPrimary: string;",
        "  textSecondary: string;",
        "  textDim: string;",
        "  accent: string;",
        "  accentHover: string;",
        "  accentSoft: string;",
        "  success: string;",
        "  warning: string;",
        "  danger: string;",
        "}",
        "",
        "export interface ThemeEntry {",
        "  id: string;",
        "  name: string;",
        "  palette: ThemePaletteTokens;",
        "}",
        "",
        "export const themeLibrary: ThemeEntry[] = [",
    ]
    for e in entries:
        p = e["palette"]
        lines.append(f"  {{")
        lines.append(f'    id: "{e["id"]}",')
        lines.append(f'    name: "{e["name"].replace(chr(34), chr(92) + chr(34))}",')
        lines.append("    palette: {")
        for k, v in p.items():
            lines.append(f'      {k}: "{v}",')
        lines.append("    },")
        lines.append("  },")
    lines.append("];")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {len(entries)} themes -> {OUT}")


if __name__ == "__main__":
    main()
