"""Chinese (user-friendly) labels for the 67 styles and 96 palettes.
Used by gen-themes.py and gen-styles.py to emit `zh` (short, plain-Chinese
alias) and `category` (top-level group) into the generated library files.
"""

# 67 style categories -> (zh, category)
# category groups: 圆润 / 方正 / 复古 / 未来 / 数据 / 极简 / 3D / 自然 / 商务 / 创意
STYLE_LABELS = {
    "Minimalism & Swiss Style": ("极简瑞士", "极简"),
    "Neumorphism": ("软浮雕", "圆润"),
    "Glassmorphism": ("毛玻璃", "圆润"),
    "Brutalism": ("粗野硬朗", "方正"),
    "3D & Hyperrealism": ("3D 拟真", "3D"),
    "Vibrant & Block-based": ("彩色色块", "创意"),
    "Dark Mode (OLED)": ("纯黑 OLED", "未来"),
    "Accessible & Ethical": ("无障碍", "极简"),
    "Claymorphism": ("黏土感", "圆润"),
    "Aurora UI": ("极光辉", "未来"),
    "Retro-Futurism": ("复古未来", "复古"),
    "Flat Design": ("扁平", "极简"),
    "Skeuomorphism": ("仿真拟物", "3D"),
    "Liquid Glass": ("液态玻璃", "圆润"),
    "Motion-Driven": ("动效驱动", "创意"),
    "Micro-interactions": ("微交互", "极简"),
    "Inclusive Design": ("包容设计", "极简"),
    "Zero Interface": ("零界面", "极简"),
    "Soft UI Evolution": ("柔和软面", "圆润"),
    "Hero-Centric Design": ("首屏大图", "商务"),
    "Conversion-Optimized": ("转化优化", "商务"),
    "Feature-Rich Showcase": ("功能展示", "商务"),
    "Minimal & Direct": ("简约直白", "极简"),
    "Social Proof-Focused": ("用户证言", "商务"),
    "Interactive Product Demo": ("交互演示", "创意"),
    "Trust & Authority": ("信任权威", "商务"),
    "Storytelling-Driven": ("叙事为主", "创意"),
    "Data-Dense Dashboard": ("数据密集", "数据"),
    "Heat Map & Heatmap Style": ("热力图", "数据"),
    "Executive Dashboard": ("高管看板", "数据"),
    "Real-Time Monitoring": ("实时监控", "数据"),
    "Drill-Down Analytics": ("下钻分析", "数据"),
    "Comparative Analysis Dashboard": ("对比分析", "数据"),
    "Predictive Analytics": ("预测分析", "数据"),
    "User Behavior Analytics": ("用户行为", "数据"),
    "Financial Dashboard": ("财务看板", "数据"),
    "Sales Intelligence Dashboard": ("销售智能", "数据"),
    "Neubrutalism": ("新粗野", "方正"),
    "Bento Box Grid": ("便当盒布局", "创意"),
    "Y2K Aesthetic": ("Y2K 千禧", "复古"),
    "Cyberpunk UI": ("赛博朋克", "未来"),
    "Organic Biophilic": ("自然亲生物", "自然"),
    "AI-Native UI": ("原生 AI", "未来"),
    "Memphis Design": ("孟菲斯", "创意"),
    "Vaporwave": ("蒸汽波", "复古"),
    "Dimensional Layering": ("层次堆叠", "3D"),
    "Exaggerated Minimalism": ("夸张极简", "极简"),
    "Kinetic Typography": ("动效字", "创意"),
    "Parallax Storytelling": ("视差叙事", "创意"),
    "Swiss Modernism 2.0": ("瑞士 2.0", "极简"),
    "HUD / Sci-Fi FUI": ("科幻 HUD", "未来"),
    "Pixel Art": ("像素风", "复古"),
    "Bento Grids": ("便当网格", "创意"),
    "Spatial UI (VisionOS)": ("空间 UI", "未来"),
    "E-Ink / Paper": ("电子墨水", "极简"),
    "Gen Z Chaos / Maximalism": ("Z 世代极繁", "创意"),
    "Biomimetic / Organic 2.0": ("仿生 2.0", "自然"),
    "Anti-Polish / Raw Aesthetic": ("不修边幅", "复古"),
    "Tactile Digital / Deformable UI": ("触感数字", "3D"),
    "Nature Distilled": ("自然简约", "自然"),
    "Interactive Cursor Design": ("交互光标", "创意"),
    "Voice-First Multimodal": ("语音优先", "未来"),
    "3D Product Preview": ("3D 商品", "3D"),
    "Gradient Mesh / Aurora Evolved": ("渐变网格", "未来"),
    "Editorial Grid / Magazine": ("编辑网格", "创意"),
    "Chromatic Aberration / RGB Split": ("RGB 分离", "复古"),
    "Vintage Analog / Retro Film": ("复古胶片", "复古"),
}

# 96 palette names -> (zh, category)
# category groups: 暗色 / 亮色 / 商务 / 游戏 / 医疗 / 教育 / 金融 / 政府 / 科技 / 生活 / 娱乐 / 设计
PALETTE_LABELS = {
    "SaaS (General)": ("SaaS 通用", "商务"),
    "Micro SaaS": ("微型 SaaS", "科技"),
    "E-commerce": ("电商", "商务"),
    "E-commerce Luxury": ("奢华电商", "商务"),
    "Service Landing Page": ("服务落地页", "商务"),
    "B2B Service": ("B2B 服务", "商务"),
    "Financial Dashboard": ("财务看板", "金融"),
    "Analytics Dashboard": ("分析看板", "数据"),
    "Healthcare App": ("医疗应用", "医疗"),
    "Educational App": ("教育应用", "教育"),
    "Creative Agency": ("创意机构", "设计"),
    "Portfolio/Personal": ("个人作品集", "设计"),
    "Gaming": ("游戏", "游戏"),
    "Government/Public Service": ("政府公共服务", "政府"),
    "Fintech/Crypto": ("金融科技", "金融"),
    "Social Media App": ("社交应用", "生活"),
    "Productivity Tool": ("效率工具", "科技"),
    "Design System/Component Library": ("设计系统", "设计"),
    "AI/Chatbot Platform": ("AI 对话", "科技"),
    "NFT/Web3 Platform": ("Web3", "科技"),
    "Creator Economy Platform": ("创作者平台", "生活"),
    "Sustainability/ESG Platform": ("可持续 / ESG", "政府"),
    "Remote Work/Collaboration Tool": ("远程协作", "科技"),
    "Mental Health App": ("心理健康", "医疗"),
    "Pet Tech App": ("宠物科技", "生活"),
    "Smart Home/IoT Dashboard": ("智能家居", "科技"),
    "EV/Charging Ecosystem": ("电动车充电", "生活"),
    "Subscription Box Service": ("订阅盒子", "生活"),
    "Podcast Platform": ("播客", "娱乐"),
    "Dating App": ("交友", "生活"),
    "Micro-Credentials/Badges Platform": ("微证书", "教育"),
    "Knowledge Base/Documentation": ("知识库", "科技"),
    "Hyperlocal Services": ("本地服务", "生活"),
    "Beauty/Spa/Wellness Service": ("美容 SPA", "生活"),
    "Luxury/Premium Brand": ("奢华品牌", "设计"),
    "Restaurant/Food Service": ("餐厅", "生活"),
    "Fitness/Gym App": ("健身", "生活"),
    "Real Estate/Property": ("房地产", "商务"),
    "Travel/Tourism Agency": ("旅游", "娱乐"),
    "Hotel/Hospitality": ("酒店", "娱乐"),
    "Wedding/Event Planning": ("婚礼策划", "生活"),
    "Legal Services": ("法律服务", "商务"),
    "Insurance Platform": ("保险", "金融"),
    "Banking/Traditional Finance": ("传统银行", "金融"),
    "Online Course/E-learning": ("在线课程", "教育"),
    "Non-profit/Charity": ("公益慈善", "政府"),
    "Music Streaming": ("音乐", "娱乐"),
    "Video Streaming/OTT": ("视频流媒体", "娱乐"),
    "Job Board/Recruitment": ("招聘", "商务"),
    "Marketplace (P2P)": ("P2P 市场", "商务"),
    "Logistics/Delivery": ("物流配送", "生活"),
    "Agriculture/Farm Tech": ("农业科技", "科技"),
    "Construction/Architecture": ("建筑", "商务"),
    "Automotive/Car Dealership": ("汽车销售", "生活"),
    "Photography Studio": ("摄影", "设计"),
    "Coworking Space": ("联合办公", "商务"),
    "Cleaning Service": ("清洁服务", "生活"),
    "Home Services (Plumber/Electrician)": ("家居维修", "生活"),
    "Childcare/Daycare": ("托儿", "生活"),
    "Senior Care/Elderly": ("养老", "医疗"),
    "Medical Clinic": ("诊所", "医疗"),
    "Pharmacy/Drug Store": ("药店", "医疗"),
    "Dental Practice": ("牙科", "医疗"),
    "Veterinary Clinic": ("兽医", "医疗"),
    "Florist/Plant Shop": ("花艺", "生活"),
    "Bakery/Cafe": ("烘焙咖啡", "生活"),
    "Coffee Shop": ("咖啡店", "生活"),
    "Brewery/Winery": ("酒庄", "生活"),
    "Airline": ("航空", "娱乐"),
    "News/Media Platform": ("新闻媒体", "娱乐"),
    "Magazine/Blog": ("杂志博客", "娱乐"),
    "Freelancer Platform": ("自由职业", "商务"),
    "Consulting Firm": ("咨询", "商务"),
    "Marketing Agency": ("营销机构", "商务"),
    "Event Management": ("活动管理", "商务"),
    "Conference/Webinar Platform": ("会议直播", "商务"),
    "Membership/Community": ("会员社区", "生活"),
    "Newsletter Platform": ("邮件简报", "科技"),
    "Digital Products/Downloads": ("数字产品", "生活"),
    "Church/Religious Organization": ("宗教组织", "政府"),
    "Sports Team/Club": ("体育俱乐部", "娱乐"),
    "Museum/Gallery": ("博物馆", "教育"),
    "Theater/Cinema": ("剧院影院", "娱乐"),
    "Language Learning App": ("语言学习", "教育"),
    "Coding Bootcamp": ("编程训练营", "教育"),
    "Cybersecurity Platform": ("网络安全", "科技"),
    "Developer Tool / IDE": ("开发工具", "科技"),
    "Biotech / Life Sciences": ("生物科技", "科技"),
    "Space Tech / Aerospace": ("航天科技", "科技"),
    "Architecture / Interior": ("建筑室内", "设计"),
    "Quantum Computing": ("量子计算", "科技"),
    "Biohacking / Longevity": ("抗衰延寿", "医疗"),
    "Autonomous Systems": ("自动驾驶", "科技"),
    "Generative AI Art": ("AI 绘画", "设计"),
    "Spatial / Vision OS": ("空间 OS", "科技"),
    "Climate Tech": ("气候科技", "科技"),
}


def style_label(name: str):
    return STYLE_LABELS.get(name, (name, "其他"))


def palette_label(name: str):
    return PALETTE_LABELS.get(name, (name, "其他"))
